### ISSUE TITLE
BiomEdit Crash

### ISSUE THREAD

**Issue by DJDosKiller** [Cube-Nation/BiomeEdit#6]
Hello, i get this error if i want to change a big biome:
2013-01-26 12:36:08 [INFO] DJDosKiller issued server command: /be set forest replace
2013-01-26 12:36:20 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?
2013-01-26 12:36:33 [SEVERE] Exception in thread "pool-1-thread-11" 
2013-01-26 12:36:33 [SEVERE] org.apache.commons.lang.UnhandledException: Plugin BiomeEdit v1.0.1 generated an exception while executing task 851
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.server.v1_4_R1.WorldChunkManager.getWetness(SourceFile:81)
    at net.minecraft.server.v1_4_R1.BiomeCacheBlock.<init>(SourceFile:28)
    at net.minecraft.server.v1_4_R1.BiomeCache.a(SourceFile:58)
    at net.minecraft.server.v1_4_R1.BiomeCache.b(SourceFile:67)
    at net.minecraft.server.v1_4_R1.WorldChunkManager.getBiome(SourceFile:61)
    at net.minecraft.server.v1_4_R1.World.getBiome(World.java:85)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBiome(CraftWorld.java:511)
    at me.derflash.plugins.cnbiomeedit.BiomeEditor.parseChunkOnMainThread(BiomeEditor.java:91)
    at me.derflash.plugins.cnbiomeedit.BiomeEditor.findBiomeArea(BiomeEditor.java:43)
    at me.derflash.plugins.cnbiomeedit.BiomeEditor$4.run(BiomeEditor.java:265)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by DerFlash** [comment]
Looks like an error in CraftBukkit or even the Minecraft core code itself. The interesting two lines here are:

> Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
> at net.minecraft.server.v1_4_R1.WorldChunkManager.getWetness(SourceFile:81)

So somehow when checking the biome for the specific chunk it fails. I'm not sure if this is "intended" or really a bug in Bukkit/Minecraft.

But here are some things you could try:
- keep in mind to use at least the latest beta of CB ( http://dl.bukkit.org/downloads/craftbukkit/ )
- try to use the [ChunkLoad](http://dev.bukkit.org/server-mods/chunkload/) plugin to ensure that all chunks of the biome is "loaded" before:
  - just add the plugin to your server
  - in the world you want to change the biome, type: `/chunkload add __global__`
  - fly over the whole biome to load it once (those chunks will stay active although you leave the area)
  - change the biome
  - disable the chunk load function again: `/chunkload remove __global__`

**Comment by twonky4** [comment]
probably solved
